services:
  - type: web
    name: fastapi-clean
    python:
      version: 3.11.11
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 