services:
  - type: web
    name: fastapi-items-api
    python:
      version: 3.11.11
    buildCommand: |
      chmod +x ./render-build.sh
      ./render-build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 